webtalk_init -webtalk_dir C:/Users/Anestman/Documents/VLSI_labs/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/tb_keyboard_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Sep 23 11:41:04 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4dd0ee2c-2360-4d0e-9da2-5defe2432b24" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f0a20c475d8d469fa912c5e82f6cf621" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "210" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8350 Eight-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "16" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "91 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "5 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "32" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "14" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "71560_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1526772844 -regid "" -xml C:/Users/Anestman/Documents/VLSI_labs/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/tb_keyboard_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Anestman/Documents/VLSI_labs/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/tb_keyboard_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Anestman/Documents/VLSI_labs/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/tb_keyboard_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
